#!/bin/sh
set -e
if [ "$1" != "--upstream-version" ]
then
  echo "Usage: $0 --upstream-version VERSION"
  exit 1
fi
upstream_version="$2"
# Create changelog entry, so build tools can find the upstream version
dch -v "$upstream_version-1" --distribution UNRELEASED --preserve "UNRELEASED"
git add debian/changelog

# format verbose "New upstream release" messages, including ANNOUNCE file
tag_time=`git cat-file tag "wine-$upstream_version"|sed -n 's/tagger .*<.*> \([0-9]*\) .*/\1/p'`
release_date=`LC_ALL=C date -u -d "@$tag_time" +"%b %-d, %Y"`
echo "New upstream release $upstream_version, released $release_date." > announce.tmp
sed -n 's/^  - \(.*\)/- \1/p' ANNOUNCE >> announce.tmp
git commit --amend -F announce.tmp
rm announce.tmp
