#!/bin/sh

set -e

if [ "$1" = "configure" ] ; then
  # add update-alternatives entries for wine and the wineapploader scripts
  # TODO: manpages
  for app in regedit regsvr32 wineboot winedbg winefile winecfg winepath ; do
    slaves="$slaves --slave /usr/bin/$app $app /usr/bin/${app}DEBSUFFIX"
  done

  PRIORITY=70
  [ DEBSUFFIX = -development ] && PRIORITY=20

  update-alternatives \
    --install /usr/bin/wine wine /usr/bin/wineDEBSUFFIX $PRIORITY \
    $slaves
fi

#DEBHELPER#

exit 0
