.TH WINE-WRAPPER 1 2013-12-30
.SH NAME
wine-wrapper \- a launcher for wine
.SH SYNOPSIS
.B wine-wrapper
[
.BI - arguments
]
.SH DESCRIPTION
.B Wine-wrapper
takes the name of the script and launches it as a wine application.
.SH OPTIONS
arguments will be passed directly to the application.
.SH AUTHOR
This script is Copyright (C) 2002 Alexendre Julliard.
